/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.exam.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.exam.controller.ResultsPanelController;
import lk.ijse.exam.utilities.AnswerPanel;

/**
 *
 * @author Imalka Gunawardana
 */
public class ResultsPanel extends javax.swing.JPanel {

    private static ResultsPanel resultsPanel;
    private TestExamPanel testExamPanel;
    private String[] dataForServer;

    /**
     * Creates new form ResultsPanel
     */
    private ResultsPanel() {
        initComponents();
        setSize(1920, 1010);
        setVisible(false);
    }

    public static ResultsPanel getInstance() {
        if (resultsPanel == null) {
            resultsPanel = new ResultsPanel();
        }
        return resultsPanel;
    }
    
    public void showResults(){
        lblMarks.setText(AnswerPanel.getCalculatedMarks() + "%");
    }

    public void setTestExamPanel(TestExamPanel testExamPanel, String[] dataForServer) {
        this.testExamPanel = testExamPanel;
        this.dataForServer = dataForServer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDivision = new javax.swing.JLabel();
        btnBackPage = new javax.swing.JLabel();
        lblMarks = new javax.swing.JLabel();
        lblDark = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(null);

        lblDivision.setFont(new java.awt.Font("Neuropol X Rg", 0, 60)); // NOI18N
        lblDivision.setForeground(new java.awt.Color(255, 102, 51));
        lblDivision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDivision.setText("Results");
        add(lblDivision);
        lblDivision.setBounds(490, 20, 940, 61);

        btnBackPage.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        btnBackPage.setForeground(new java.awt.Color(204, 204, 204));
        btnBackPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/exam/asset/Left_96px.png"))); // NOI18N
        btnBackPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackPageMouseClicked(evt);
            }
        });
        add(btnBackPage);
        btnBackPage.setBounds(20, 20, 250, 70);

        lblMarks.setFont(new java.awt.Font("Consolas", 0, 50)); // NOI18N
        lblMarks.setForeground(new java.awt.Color(204, 204, 204));
        lblMarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarks.setText("23");
        add(lblMarks);
        lblMarks.setBounds(600, 360, 690, 140);

        lblDark.setBackground(new Color(0,0,0,170));
        lblDark.setOpaque(true);
        add(lblDark);
        lblDark.setBounds(0, 0, 1920, 1010);

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/exam/asset/macos_sierra_2-wallpaper-1920x1080.jpg"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(0, -70, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPageMouseClicked
        try {
            this.setVisible(false);
            dataForServer[4] = "Unregister";
            ResultsPanelController.getTeacherSubject().notifyObservers(1);
            testExamPanel.setVisible(true);
            try {
                ResultsPanelController.getTeacherSubject().notifyObservers(1);
            } catch (Exception ex) {
                Logger.getLogger(ResultsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(ResultsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackPageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackPage;
    private javax.swing.JLabel lblDark;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMarks;
    // End of variables declaration//GEN-END:variables
}
